const path = require('path');
const fs = require('fs');
const jwt = require('jsonwebtoken');
const privateKeyPath = path.join(__dirname, '../../keys/private.key');
const publicKeyPath = path.join(__dirname, '../../keys/public.key');

/**
 * keys generated by https://travistidwell.com/jsencrypt/demo/
 * The algo must be set to "RS256"
 */

// keys (must read as 'UTF-8')
const privateKey = fs.readFileSync(privateKeyPath, 'utf8');
const publicKey = fs.readFileSync(publicKeyPath, 'utf8');

// value for rfc7519 fields
const iss = "hoola@hoola.com"; // company name
const sub = "user@gmail.com"; // user of the token
const aud = "https://hamza.com"; // where token consume
const exp = "24h"; // expire time


const payload = {
    email: "hamza@hamza.com"
}

const signOptions = {
    issuer: iss,
    subject: sub,
    audience: aud,
    expiresIn: exp,
    algorithm: "RS256"
};


const token = jwt.sign(payload, privateKey, signOptions);
console.log("token: ", token);

const verifyOptions = {
    issuer: iss,
    subject: sub,
    audience: aud,
    maxAge: exp,
    algorithm: "RS256"
};

const verified = jwt.verify(token, publicKey, verifyOptions);
// verified
console.log(JSON.stringify(verified));

const decode = jwt.decode(token, { complete: true });

// decode header
console.log(JSON.stringify(decode.header));
// decode payload
console.log(JSON.stringify(decode.payload));